//! OpenAI API types generated from OpenAPI specification
//!
//! This crate provides strongly-typed request and response structures
//! for the OpenAI API, generated using Progenitor from the official
//! OpenAPI specification.

// Placeholder - types will be generated by build script